name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install nodejs dependencies
        run: |
          yarn
      - name: Run Webpack Build
        run: |
          yarn production
      - name: stage, commit, fetch, push
        run: |
          git add .
          git commit -m "[AUTO:BUILD] build main.js"
          git fetch origin master
          git push origin HEAD:master